# version: "3.8"

services:
  vite-app:
    container_name: vite-react-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    environment:
      - NODE_ENV=production
